### ISSUE TITLE
[Error 2] "build.py serve"

### ISSUE THREAD

**Issue by gdini** [buddebej/ol3-dem#1]
Hi,
I was trying to get some tests with your app.
I cloned the repository on my Windows7 machine, but so far I can't get the example working.
Opening the "./build.py serve" always returns an error (Error 2).

Could please  pass me some instruction to get started with this example? 
For instance, which dependancies do I need, any configuration that is not included in the repository, etc.?

I already checked the dependancies (https://github.com/openlayers/ol3/blob/b26bea8e88364f7c402c9dafd87816b4e93f75e1/CONTRIBUTING.md) and there are all installed.

Thanks in advance.
Best regards

**Comment by donSchoe** [comment]
can confirm this with linux. both python2 and python3 complain about invalid syntax.

```
 me@comp ~/opt/ol3-dem/ol3 $ python2 --version
Python 2.7.10

 me@comp ~/opt/ol3-dem/ol3 $ python3 --version
Python 3.4.3

 me@comp ~/opt/ol3-dem/ol3 $ python2 ./build.py serve
2015-09-16 10:27:41,900 examples/example-list.js: python bin/exampleparser.py examples examples
  File "bin/exampleparser.py", line 26
    except ImportError, E:
                      ^
SyntaxError: invalid syntax
2015-09-16 10:27:41,944 examples/example-list.js: clean
2015-09-16 10:27:41,945 pake: examples/example-list.js: Command '['python', 'bin/exampleparser.py', 'examples', 'examples']' returned non-zero exit status 1

 me@comp ~/opt/ol3-dem/ol3 $ python2 ./build.py
2015-09-16 10:27:44,609 build/npm-install-timestamp: mkdir -p build
2015-09-16 10:27:44,609 build/npm-install-timestamp: npm install
Traceback (most recent call last):
  File "./build.py", line 811, in <module>
    main()
  File "/home/me/opt/ol3-dem/ol3/pake.py", line 442, in main
    target.build(dry_run=options.dry_run)
  File "/home/me/opt/ol3-dem/ol3/pake.py", line 109, in build
    timestamp = max(timestamp, target.build(dry_run=dry_run))
  File "/home/me/opt/ol3-dem/ol3/pake.py", line 109, in build
    timestamp = max(timestamp, target.build(dry_run=dry_run))
  File "/home/me/opt/ol3-dem/ol3/pake.py", line 109, in build
    timestamp = max(timestamp, target.build(dry_run=dry_run))
  File "/home/me/opt/ol3-dem/ol3/pake.py", line 124, in build
    self.action(self)
  File "./build.py", line 187, in npm_install
    t.run('npm', 'install')
  File "/home/me/opt/ol3-dem/ol3/pake.py", line 233, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

 me@comp ~/opt/ol3-dem/ol3 $ python3 ./build.py serve
  File "./build.py", line 37
    print '{0}. {1}'.format(count, thing)
                   ^
SyntaxError: invalid syntax

 me@comp ~/opt/ol3-dem/ol3 $ python3 ./build.py
  File "./build.py", line 37
    print '{0}. {1}'.format(count, thing)
                   ^
SyntaxError: invalid syntax
```
